-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module SmoothTerminal.Object exposing (..)


type Author
    = Author


type BlogPost
    = BlogPost


type Drip
    = Drip


type FirestormPost
    = FirestormPost


type FirestormThread
    = FirestormThread


type FirestormUser
    = FirestormUser


type PaginatedArticles
    = PaginatedArticles


type PaginatedStories
    = PaginatedStories


type Story
    = Story


type Tag
    = Tag
