-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module SmoothTerminal.Object.FirestormPost exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SmoothTerminal.InputObject
import SmoothTerminal.Interface
import SmoothTerminal.Object
import SmoothTerminal.Scalar
import SmoothTerminal.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) SmoothTerminal.Object.FirestormPost
selection constructor =
    Object.selection constructor


body : Field String SmoothTerminal.Object.FirestormPost
body =
    Object.fieldDecoder "body" [] Decode.string


id : Field SmoothTerminal.Scalar.Id SmoothTerminal.Object.FirestormPost
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map SmoothTerminal.Scalar.Id)


insertedAt : Field SmoothTerminal.Scalar.DateTime SmoothTerminal.Object.FirestormPost
insertedAt =
    Object.fieldDecoder "insertedAt" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map SmoothTerminal.Scalar.DateTime)


user : SelectionSet decodesTo SmoothTerminal.Object.FirestormUser -> Field decodesTo SmoothTerminal.Object.FirestormPost
user object =
    Object.selectionField "user" [] object identity
