-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module SmoothTerminal.Object.PaginatedArticles exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SmoothTerminal.InputObject
import SmoothTerminal.Interface
import SmoothTerminal.Object
import SmoothTerminal.Scalar
import SmoothTerminal.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) SmoothTerminal.Object.PaginatedArticles
selection constructor =
    Object.selection constructor


entries : SelectionSet decodesTo SmoothTerminal.Union.Article -> Field (Maybe (List (Maybe decodesTo))) SmoothTerminal.Object.PaginatedArticles
entries object =
    Object.selectionField "entries" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


pageNumber : Field (Maybe Int) SmoothTerminal.Object.PaginatedArticles
pageNumber =
    Object.fieldDecoder "pageNumber" [] (Decode.int |> Decode.nullable)


pageSize : Field (Maybe Int) SmoothTerminal.Object.PaginatedArticles
pageSize =
    Object.fieldDecoder "pageSize" [] (Decode.int |> Decode.nullable)


totalEntries : Field (Maybe Int) SmoothTerminal.Object.PaginatedArticles
totalEntries =
    Object.fieldDecoder "totalEntries" [] (Decode.int |> Decode.nullable)


totalPages : Field (Maybe Int) SmoothTerminal.Object.PaginatedArticles
totalPages =
    Object.fieldDecoder "totalPages" [] (Decode.int |> Decode.nullable)
