-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module SmoothTerminal.Union.Article exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (FragmentSelectionSet(FragmentSelectionSet), SelectionSet(SelectionSet))
import Json.Decode as Decode
import SmoothTerminal.InputObject
import SmoothTerminal.Interface
import SmoothTerminal.Object
import SmoothTerminal.Scalar
import SmoothTerminal.Union


selection : (Maybe typeSpecific -> constructor) -> List (FragmentSelectionSet typeSpecific SmoothTerminal.Union.Article) -> SelectionSet constructor SmoothTerminal.Union.Article
selection constructor typeSpecificDecoders =
    Object.unionSelection typeSpecificDecoders constructor


onBlogPost : SelectionSet decodesTo SmoothTerminal.Object.BlogPost -> FragmentSelectionSet decodesTo SmoothTerminal.Union.Article
onBlogPost (SelectionSet fields decoder) =
    FragmentSelectionSet "BlogPost" fields decoder


onDrip : SelectionSet decodesTo SmoothTerminal.Object.Drip -> FragmentSelectionSet decodesTo SmoothTerminal.Union.Article
onDrip (SelectionSet fields decoder) =
    FragmentSelectionSet "Drip" fields decoder
